# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR UPR Team <info@privacy-cd.org>
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: extended-volume-manager 0.1\n"
"Report-Msgid-Bugs-To: info@discreete-linux.org\n"
"POT-Creation-Date: 2017-03-02 11:12+0100\n"
"PO-Revision-Date: 2017-03-02 11:16+0100\n"
"Last-Translator: Discreete Linux Team <info@discreete-linux.org>\n"
"Language-Team: LANGUAGE <de@li.org>\n"
"Language: de\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: Poedit 1.6.10\n"

#: extvol-device-listener.py:20
msgid "Extended volume"
msgstr "Erweiterter Container"

#: extvol-device-listener.py:21
msgid ""
"This appears to be an extended Volume. Do you want to make use of the "
"settings stored therein?"
msgstr ""
"Dies scheint ein erweiterter Container zu sein. Wollen Sie die darin "
"gespeicherten Einstellungen benutzen?"

#: extvol-close:14
msgid "Too many arguments."
msgstr "Zu viele Argumente."

#: extvol-manager.py:60
msgid "Close extended volume"
msgstr "Erweiterten Container schließen"

#: extvol-manager.py:62
msgid "Closes and Unmounts the selected extended Volume"
msgstr "Schließt des ausgewählten erweiterten Container"

#: extvolmanager.py:112
#, python-format
msgid ""
"A system error occured. The error was\n"
"\n"
"%(error)s\n"
"\n"
"Local variables:\n"
"%(vars)s"
msgstr ""
"Ein Systemfehler ist aufgetreten. Der Fehler war\n"
"\n"
"%(error)s\n"
"\n"
"Lokale Variablen:\n"
"%(vars)s"

#: extvolmanager.py:169
#, python-format
msgid "Could not set permissions and/or ownership on %s"
msgstr "Konnte Rechte und/oder Eigentümer auf %s nicht setzen"

#: extvolmanager.py:205 extvolmanager.py:226
msgid "Do you want to da a backup?"
msgstr "Wollen Sie ihre Daten sichern?"

#: extvolmanager.py:206
#, python-format
msgid ""
"It looks like you have a backup container/volume mounted at /media/backup. "
"Do you want to use it for a backup of your files in %s?"
msgstr ""
"Es scheint, als wäre bereits ein Backup-Container auf /media/backup "
"geöffnet. Soll er für eine Sicherung der Daten im Container %s verwendet "
"werden?"

#: extvolmanager.py:218
msgid ""
"More than one possible backup container or device was found. Automatic "
"backup cannot continue. Please make sure only one backup container or device "
"is present.\n"
"\n"
"I have found these containers and devices:\n"
msgstr ""
"Es wurde mehr als ein möglicher Backup-Container oder -Gerät gefunden. Das "
"automatische Backup kann nicht ausgeführt werden. Bitte stellen Sie sicher, "
"dass nur ein Backup-Container oder -Gerät existiert.\n"
"\n"
"Ich habe folgende Geräte und Container gefunden:\n"

#: extvolmanager.py:227
#, python-format
msgid ""
"%(backupname)s looks like an encrypted backup container. Do you want to use "
"it for a backup of your files in %(origname)s? If you answer with \"OK\", "
"you will have to enter the password for %(backupname)s in the next step."
msgstr ""
"%(backupname)s scheint ein verschlüsselter Backup-Container zu sein. Soll er "
"für eine Sicherung der Daten im Container %(origname)s verwendet werden? "
"Wenn Sie mit \"OK\" antworten, müssen Sie im nächsten Schritt das Passwort "
"für den Container %(backupname)s eingeben"

#: extvolmanager.py:239
#, python-format
msgid ""
"%(backupname)s is not an \"extended volume\" and can therefore not be used "
"for a backup.\n"
"Please convert %(backupname)s to an \"extended Volume\" or create a new, "
"ext3 formatted backup volume with name backup.tc."
msgstr ""
"%(backupname)s ist kein \"erweiterter Container\" und kann deshalb nicht für "
"ein Backup verwendet werden.\n"
"Bitte konvertieren Sie %(backupname)s zu einem \"erweiterten Truecrypt-"
"Container\" oder legen Sie einen neuen, ext3-formatierten Backup-Container "
"mit dem Namen backup.tc an."

#: extvolmanager.py:250
msgid "Unmounting"
msgstr "Aushängen"

#: extvolmanager.py:250
msgid "Please wait until all data has been written to disk..."
msgstr "Bitte warten, bis alle Daten auf Datenträger geschrieben wurden..."

#: extvolmanager.py:269
msgid ""
"An error occured during backup!\n"
"Could not create target directory."
msgstr ""
"Beim Backup ist ein Fehler aufgetreten!\n"
"Konnte Zielverzeichnis nicht erstellen."

#: extvolmanager.py:285
msgid "An error occured during backup. Error occured while executing gtkrsync!"
msgstr ""
"Beim Backup ist ein Fehler aufgetreten!\n"
"Ein Fehler trat auf beim Ausführen von gtkrsync!"

#: extvolmanager.py:293 extvolmanager.py:318
#, python-format
msgid "Could not delete incomplete backup at %s"
msgstr "Konnte unvollständiges Backup auf %s nicht löschen"

#: extvolmanager.py:298
msgid "Cleaning up"
msgstr "Aufräumen"

#: extvolmanager.py:298
msgid "Old backups are being cleaned up, please wait..."
msgstr "Alte Backups werden aufgeräumt, bitte warten..."

#: extvolmanager.py:305
#, python-format
msgid "Could not delete old backup at %s"
msgstr "Konnte altes Backup auf %s nicht löschen"

#: extvolmanager.py:308
msgid "Backup done."
msgstr "Backup abgeschlossen."

#: extvolmanager.py:309
#, python-format
msgid "Backup of %s successful."
msgstr "Backup von %s erfolgreich."

#: extvolmanager.py:313
msgid ""
"An error occured during backup!\n"
"Maybe there is not enough space at the destination."
msgstr ""
"Beim Backup ist ein Fehler aufgetreten!\n"
"Eventuell ist am Ziel nicht genügend Platz."

#: extvolmanager.py:351
msgid "Backup other containers?"
msgstr "Andere Container sichern?"

#: extvolmanager.py:352
#, python-format
msgid ""
"You can now backup your other open containers as well. Their contents will "
"be stored within the same backup container, but in a separate directory. Do "
"you want to do this now?\n"
"\n"
"Hint: The backup container has %s free space."
msgstr ""
"Sie können jetzt auch andere geöffnete Container mit sichern. Ihr Inhalt "
"wird im gleichen Backup-Container, aber in einem extra Ordner gespeichert. "
"Wollen Sie das jetzt tun?\n"
"\n"
"Hinweis: Der Backup-Container hat noch %s frei."

#: extvolmanager.py:540
msgid ""
"Failed to stop evolution, will skip loading evolution data from the extended "
"container!"
msgstr ""
"Konnte Evolution nicht anhalten, überspringe das Laden der Evolution-Daten "
"vom erweiterten Container!"

#: extvolmanager.py:719
#, python-format
msgid ""
"Multiple virtual machines were found on %s, don't know which one to start. "
"Please start it manually."
msgstr ""
"Mehrere virtuelle Maschinen wurden auf %s gefunden, weiss nicht welche "
"gestartet werden soll. Bitte manuell starten."

#: extvolmanager.py:723
msgid "Start Virtual Machine?"
msgstr "Virtuelle Maschine starten?"

#: extvolmanager.py:724
#, python-format
msgid ""
"A virtual machine named \n"
"%s\n"
" was found. Do you want to start it?"
msgstr ""
"Eine virtuelle Maschine namens\n"
"%s\n"
"wurde gefunden. Soll sie gestartet werden?"

#: extvolmanager.py:729
#, python-format
msgid ""
"An error occured trying to start the virtual machine:\n"
"%s"
msgstr ""
"Ein Fehler trat auf beim Versuch, die virtuelle Maschine:\n"
"%s\n"
"zu starten."

#: extvolmanager.py:817
msgid "An error occured while checking the backup configuration."
msgstr "Ein Fehler trat auf bei der Prüfung der Backup-Einstellungen."

#: extvolmanager.py:825
msgid "An error occured while trying to run a (last) snapshot."
msgstr ""
"Ein Fehler trat auf beim Versuch, einen (letzten) Schnappschuss zu erstellen."

#: extvolmanager.py:829
msgid ""
"You seem to be opening this extended container for the first time with this "
"version. Please be aware of the following:\n"
"* Evolution data cannot be migrated. Please open with the old version "
"instead, make a data backup within evolution and restore it using this new "
"version.\n"
"* The password manager database will be converted and cannot be opened with "
"older versions afterwards.\n"
"* Some seahorse settings cannot be migrated and need tobe re-done. This does "
"not affect your keys or GnuPG settings.\n"
"* Beagle is not supported anymore, but its data will remain on the "
"container. You may manually delete the folder '.beagle'.\n"
"\n"
"\n"
"<b>Do you want to continue and open this extended container?</b>"
msgstr ""
"Sie öffnen diesen erweiterten Container offenbar zum ersten Mal mit dieser "
"Version. Bitte beachten Sie folgendes:\n"
"* Evolution-Daten können nicht übernommen werden. Bitte statt dessen mit der "
"alten Version öffnen, in Evolution eine Datensicherung durchführen und diese "
"in der neuen Version importieren.\n"
"* Die Passwort-Manager-Datenbank wird konvertiert und kann danach mit "
"älteren Versionen u.U. nicht mehr geöffnet werden.\n"
"* Einige Einstellungen der Schlüsselverwaltung Seahorse können nicht "
"übernommen werden. Dies betrifft nicht die Schlüssel oder GnuPG-"
"Einstellungen.\n"
"* Beagle Volltextsuche wird nicht mehr unterstützt, aber die Daten "
"verbleiben im Container. Sie können den Ordner \".beagle\" manuell löschen.\n"
"\n"
"\n"
"<b>Wollen Sie fortfahren und diesen erweiterten Container öffnen?</b>"

#: extvolmanager.py:845
msgid "New Version"
msgstr "Neue Version"

#: extvolmanager.py:857
msgid ""
"Either this is not an extended volume, or there is already another extended "
"volume mounted. There can only be one extended volume mounted at a time."
msgstr ""
"Entweder ist dies kein erweiterter Container, oder es ist bereits ein "
"anderer erweiterter Container eingehängt. Es kann immer nur ein erweiterter "
"Container gleichzeitig eingehängt sein."

#: extvolmanager.py:869
msgid "Low free space"
msgstr "Wenig freier Speicherplatz"

#: extvolmanager.py:870
#, python-format
msgid ""
"There are only %(freebytes)s free on %(volume)s. This may cause problems "
"when using it as an extended volume. You should stop now, free some space "
"and then try re-opening this as an extended volume again.\n"
"\n"
"Stop now?"
msgstr ""
"Es sind nur noch %(freebytes)s frei auf %(volume)s. Das kann Probleme "
"verursachen beim Verwenden als erweiterter Container. Sie sollten jetzt "
"abbrechen, etwas Speicherplatz schaffen und den Container erneut als "
"erweiterten öffnen.\n"
"\n"
"Jetz abbrechen?"

#: extvolmanager.py:886 extvolmanager.py:945
msgid "Please wait..."
msgstr "Bitte warten..."

#: extvolmanager.py:887
msgid "Extended volume is being opened, please wait!"
msgstr "Erweiterter Container wird geöffnet, bitte warten!"

#: extvolmanager.py:920
msgid "Opening successful"
msgstr "Öffnen erfolgreich"

#: extvolmanager.py:921
msgid "Extended volume opened successfully."
msgstr "Erweiterter Container wurde erfolgreich geöffnet."

#: extvolmanager.py:941
#, python-format
msgid ""
"There are still open files on %s, listed below. Please close them first.\n"
"\n"
msgstr ""
"Es sind noch Dateien auf %s geöffnet, die unten aufgelistet sind.Bitte diese "
"zuerst schließen und erneut versuchen.\n"
"\n"

#: extvolmanager.py:945
msgid "Extended volume is being closed, please wait!"
msgstr "Erweiterter Container wird geschlossen, bitte warten!"

#: extvolmanager.py:991
#, python-format
msgid "Unmounting the volume at %s failed!"
msgstr "Aushängen des Volumes auf %s fehlgeschlagen!"

#: extvolmanager.py:993
msgid "Closing successful"
msgstr "Schließen erfolgreich"

#: extvolmanager.py:993
msgid "Extended volume closed successfully!"
msgstr "Erweiterter Container wurde erfolgreich geschlossen."

msgid "Extended volume listener"
msgstr "Extended volume listener"

msgid "Listens for mounted volumes which could be extended volumes"
msgstr ""
"Sucht nach eingehängten Datenträgern, die \"erweiterte Volumes\" sein "
"könnten."

#~ msgid "TrueCrypt helper device listener"
#~ msgstr "TrueCrypt Geräteerkennung"

#~ msgid "Scan for TrueCrypt Volumes"
#~ msgstr "Suche nach TrueCrypt-Volumes"

#~ msgid "Scans for already connected but not yet mounted TrueCrypt Volumes"
#~ msgstr ""
#~ "Sucht nach bereits angeschlossenen, aber nicht geöffneten TrueCrypt-"
#~ "Volumes"
